-- Create table
DROP TABLE application IF EXISTS;
DROP TABLE contact IF EXISTS;
CREATE TABLE application (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  dt_created   DATE,
  product_name VARCHAR(255) NOT NULL,
  contact_id   BIGINT,
  PRIMARY KEY (id)
);
CREATE TABLE contact (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY (id)
);

-- Fill table in the data
INSERT INTO contact (id) VALUES (1);
INSERT INTO application (id, contact_id, dt_created, product_name) VALUES (NULL, 1, '2015-01-01', 'app1_1');
INSERT INTO application (id, contact_id, dt_created, product_name) VALUES (NULL, 1, '2015-01-02', 'app2_1');
